<?php
define('CHECKER_ONE_SPACE', ' ');
define('CHECKER_ONE_TAB', '\t');
define('CHECKER_ONE_BLANK', '('.CHECKER_ONE_SPACE.'|'.CHECKER_ONE_TAB.')');

define('CHECKER_ONE_WINDOWS_END_LINE', '\r\n');
define('CHECKER_ONE_UNIX_END_LINE', '\n');

define('CHECKER_ONE_END_LINE', '('.CHECKER_ONE_WINDOWS_END_LINE.'|'.CHECKER_ONE_UNIX_END_LINE.')');
define('CHECKER_END_LINE_WITH_SPACE', '('.CHECKER_ONE_SPACE.'*('.CHECKER_ONE_WINDOWS_END_LINE.'|'.CHECKER_ONE_UNIX_END_LINE.'))');

define('CHECKER_MORE_THEN_ONE_SPACE', CHECKER_ONE_SPACE.'+');
define('CHECKER_MORE_THEN_ZERO_SPACE', CHECKER_ONE_SPACE.'*');

define('CHECKER_ONE_SPACES_OR_ONE_END_LINES', '[' . '('.CHECKER_ONE_WINDOWS_END_LINE.')' . CHECKER_ONE_UNIX_END_LINE . CHECKER_ONE_SPACE . ']');

define('CHECKER_BOM', '\xEF');

define('CHECKER_METHOD_KEYWORD', '(abstract |final )?(public |protected |private )+(static )?');

define('CHECKER_UNDERLINE_CASE', '_{0,2}[a-zA-Z0-9]+_');